src/core/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.views.debug import default_urlconf

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", include("pos.urls")),
    path('', default_urlconf, name='index'),
]

src/pos/urls.py
from django.urls import path, re_path

from . import views

app_name = "pos"

urlpatterns = [
    path("menus/", views.IndexView.as_view(), name="index"),
    path("orders/", views.OrderIndexView.as_view(), name="order-index"),
    path("menus/create/", views.CreateView.as_view(), name="create"),
    re_path(r"^menus/(?P<pk>[\w-]+)/$", views.UpdateView.as_view(), name="update"),
    re_path(
        r"^menus/detail/(?P<pk>[\w-]+)/$", views.DetailView.as_view(), name="detail"
    ),
    re_path(
        r"^orders/create/(?P<menu_id>[\w-]+)/$",
        views.OrderCreateView.as_view(),
        name="order-create",
    ),
]

src/pos/models.py
from uuid import uuid4
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.utils.timezone import localdate
from django.contrib.auth import get_user_model
from django_currentuser.db.models import CurrentUserField
from pos.validators import validate_date


class ResourceModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Menu(ResourceModel):
    option_1 = models.CharField(max_length=100)
    option_2 = models.CharField(max_length=100)
    option_3 = models.CharField(max_length=100)
    option_4 = models.CharField(max_length=100)
    date_at = models.DateField(validators=[validate_date])


class Order(ResourceModel):
    class MenuOptions(models.TextChoices):
        OPTION_1 = "OPTION_1", "Option 1"
        OPTION_2 = "OPTION_2", "Option 2"
        OPTION_3 = "OPTION_3", "Option 3"
        OPTION_4 = "OPTION_4", "Option 4"

    user = CurrentUserField()
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    option = models.CharField(max_length=100, choices=MenuOptions.choices)
    preference = models.CharField(max_length=100, blank=True, null=True)

src/pos/forms.py
from django.forms import ModelForm
from pos.models import Menu, Order


class MenuForm(ModelForm):
    class Meta:
        model = Menu
        fields = ["option_1", "option_2", "option_3", "option_4", "date_at"]


class OrderForm(ModelForm):
    """The form for employees to fill their
    preferred day's meal"""

    class Meta:
        model = Order
        fields = "__all__"
        exclude = {"user", "menu"}
        labels = {
            "user": "the user",
            "option": "Choose your preferred meal",
            "preference": "Any custom preference?",
        }

src/pos/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import redirect

from core.settings import LOGGER
from pos.models import Menu, Order
from pos.forms import MenuForm, OrderForm
from pos.task import slack_notification
from pos.mixins import SuperuserRequiredMixin


class IndexView(LoginRequiredMixin, SuperuserRequiredMixin, ListView):
    context_object_name = "latest_menu_list"

    def get_queryset(self):
        return Menu.objects.order_by("created_at")


class OrderIndexView(LoginRequiredMixin, SuperuserRequiredMixin, ListView):
    context_object_name = "latest_order_list"

    def get_queryset(self):
        return Order.objects.order_by("created_at")


class OrderCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Order
    form_class = OrderForm
    success_message = "Order was created successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["menu"] = Menu.objects.get(pk=self.kwargs["menu_id"])
        return context

    def form_valid(self, form):
        form.instance.menu = Menu.objects.get(pk=self.kwargs["menu_id"])
        super(OrderCreateView, self).form_valid(form)
        return redirect(
            reverse_lazy("pos:detail", kwargs={"pk": self.kwargs["menu_id"]})
        )

    def get_success_url(self) -> str:
        return reverse_lazy("pos:detail", kwargs={"pk": self.kwargs["menu_id"]})


class CreateView(
    LoginRequiredMixin, SuperuserRequiredMixin, SuccessMessageMixin, CreateView
):
    model = Menu
    form_class = MenuForm
    success_url = reverse_lazy("pos:index")
    success_message = "Menu was created successfully"

    def post(self, request):
        response = super(CreateView, self).post(request)

        try:
            slack_notification.delay(self.object.id)
            messages.info(request, "A notification has been sent to all users")
        except Exception as error:
            messages.error(request, error)
            LOGGER.error(error)

        return response


class DetailView(DetailView):
    model = Menu

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        if not self.request.user.is_anonymous:
            context["order"] = Order.objects.filter(
                user=self.request.user, menu=self.kwargs["pk"]
            ).first()
        return context


class UpdateView(
    LoginRequiredMixin, SuperuserRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = Menu
    form_class = MenuForm
    success_url = reverse_lazy("pos:index")
    success_message = "Menu was updated successfully"


class DeleteView(LoginRequiredMixin, DeleteView):
    model = Menu
    success_url = reverse_lazy("pos:index")

src/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Cornershop Backend Test{% endblock %}</title>
</head>
<body>
  <main>
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  {% if user.is_authenticated %}
  <p id="greeter">Hi {{ user.username }}!</a>
  <nav>
    <ul>
      <li><a href="{% url "home" %}">Home</a></li>
      {% if user.is_superuser %}
      <li><a href="{% url "pos:index" %}">Menus</a></li>
      <li><a href="{% url "pos:order-index" %}">Orders</a></li>
      {% else %}
      <li><a href="{% url "pos:order-index" %}">Your Orders</a></li>
      {% endif %}
      <hr>
      <li><a href="{% url "logout" %}">Logout</a></li>
    </ul>
  </nav>
  {% endif %}
  {% block content %}{% endblock %}
  </main>
</body>
</html>

src/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <h1>Home</h1>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

src/templates/pos/menu_detail.html
{% extends 'base.html' %}
{% block content %}

<table>
    <tr>
        <th>Menu</th>
        <td id="menu_id">{{ menu.id }}</td>
    </tr>
    {% if order %}
    <tr>
        <th>Order</th>
        <td id="order_id">{{ order.id }}</td>
    </tr>
    {% endif %}
</table>
{% if order %}
<h2 id="title">We're preparing your meal!</h2>
{% else %}

<h2> Hello! I share with you today's menu :)</h2>
{% include "pos/menu_options.html" %}
<h2> Have a nice day! </h2>  
<hr/>
    <a href="{% url "pos:order-create" menu_id=menu.id %}">Go to order</a> 
<hr/>
{% endif %}
{% endblock %}

src/templates/pos/menu_form.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
<h1>Menu: {{ menu.id }}</h1>
{% else %}
<h1>Create Menu</h1>
{% endif %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <a href="{% url 'pos:index' %}">Cancel</a>
    <input type="submit" value="Save Menu">
</form>
{% endblock %}

src/templates/pos/menu_list.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'pos:create' %}">Create Menu</a>


<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Option 1</th>
            <th>Option 2</th>
            <th>Option 3</th>
	        <th>Option 4</th>
            <th>Date At</th>
            <th>Created At</th>
            <th>Updated At</th>
        </tr>
    </thead>
    <tbody>
        {% if latest_menu_list %}
        {% for menu in latest_menu_list %}
            <tr>
                <td><a href="{% url 'pos:update' menu.id %}">{{ menu.id }}</a></td>
                <td>{{ menu.option_1 }}</td>
                <td>{{ menu.option_2 }}</td>
		        <td>{{ menu.option_3 }}</td>
		        <td>{{ menu.option_4 }}</td>
                <td>{{ menu.date_at }}</td>
                <td>{{ menu.created_at }}</td>
                <td>{{ menu.updated_at }}</td>
            </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td>
                <p>No menus are available.</p>
            </td>
        </tr>
        {% endif %}
    </tbody>
</table>

{% endblock %}

src/templates/pos/menu_options.html
<ul>
    <li>Option 1: {{ menu.option_1 }}</li>
    <li>Option 2: {{ menu.option_2 }}</li>
    <li>Option 3: {{ menu.option_3 }}</li>
    <li>Option 4: {{ menu.option_4 }}</li>
</ul>

src/templates/pos/order_form.html
{% extends 'base.html' %}
{% block content %}

    <h1 id="title">Create Order</h1>

    {% include "pos/menu_options.html" %}

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save Order">
    </form>
{% endblock %}

src/templates/pos/order_list.html
{% extends 'base.html' %}

{% block content %}

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>User</th>
            <th>Menu</th>
            <th>Option</th>
	        <th>Custom Preference</th>
            <th>Created At</th>
            <th>Updated At</th>
        </tr>
    </thead>
    <tbody>
        {% if latest_order_list %}
        {% for order in latest_order_list %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.user }}</td>
                <td>{{ order.menu }}</td>
		        <td>{{ order.option }}</td>
		        <td>{{ order.preference }}</td>
                <td>{{ menu.created_at }}</td>
                <td>{{ menu.updated_at }}</td>
            </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td>
                <p>No Orders are available.</p>
            </td>
        </tr>
        {% endif %}
    </tbody>
</table>

{% endblock %}